language: php

php:
   - 5.6

services:
  - mysql
  - mongodb

before_install:
  # Enable ext-mongo.
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  # Ensure newest composer and dependencies state.
  - composer self-update || true
  - composer update
  # Prepare databases.
  - mysql -e "create database IF NOT EXISTS symfony;" -uroot
  - mongo mydb_test --eval 'db.addUser("travis", "test");'

script:
  # Output configuration to see if it works.
  - php app/console config:dump-reference h4cc_alice_fixtures
  # Load fixtures one time.
  - php app/console h4cc_alice_fixtures:load:files --drop --manager odm src/h4cc/AliceDemoBundle/DataFixtures/Alice/mongodb.yml
  - php app/console h4cc_alice_fixtures:load:sets --manager orm
  - php app/console  h4cc_alice_demo:travis:check && echo "Successfully loaded Fixtures"
  # Load fixtures another time to be sure it works repeatedly.
  - php app/console h4cc_alice_fixtures:load:files --drop --manager odm src/h4cc/AliceDemoBundle/DataFixtures/Alice/mongodb.yml
  - php app/console h4cc_alice_fixtures:load:sets --manager orm
  - php app/console  h4cc_alice_demo:travis:check && echo "Successfully loaded Fixtures ... again"
