#
# This file is part of the h4cc/AliceDemo package.
#
# (c) Julius Beckmann <github@h4cc.de>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#


# --- A simple set of testdata ---


\h4cc\AliceDemoBundle\Entity\User:
  # 4 more personalized
  user{Alice, Bob, Max, Moriz}:
    name: <current()>
    email:  <current()>@example.com
  # More users
  user{1..10}:
    name: RandomUser<current()>
    email: user<current()>@example.com

\h4cc\AliceDemoBundle\Entity\Post:
  # Random Posts
  post{1..100}:
    title: <sentence()>
    content: <text(2000)>
    user: @user*
    category: <postCategory()>
