parameters:
#    h4cc_alice_customer.example.class: h4cc\AliceCustomerBundle\Example

services:
#    h4cc_alice_customer.example:
#        class: %h4cc_alice_customer.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
