
#
# This file is part of the h4cc/AliceDemo package.
#
# (c) Julius Beckmann <github@h4cc.de>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#

h4cc_alicedemo_selenium:
    resource: "@h4ccAliceDemoBundle/Controller/SeleniumController.php"
    type:     annotation
