
#
# This file is part of the h4cc/AliceDemo package.
#
# (c) Julius Beckmann <github@h4cc.de>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#


h4cc_alicedemo_default:
    resource: "@h4ccAliceDemoBundle/Controller/DefaultController.php"
    type:     annotation

h4cc_alicedemo_user:
    resource: "@h4ccAliceDemoBundle/Controller/UserController.php"
    type:     annotation

h4cc_alicedemo_post:
    resource: "@h4ccAliceDemoBundle/Controller/PostController.php"
    type:     annotation
